---
version: 1

kind: experiment

build:
  dockerfile: polyaxon/dual_bert/experiment.Dockerfile

environment:
  persistence:
    data: ["100e-nlp-lab-data"]
  resources:
    gpu:
      requests: 1
      limits: 1

framework: pytorch

logging:
  level: INFO

run:
  cmd: python -m sgnlp.models.dual_bert.train