name: span_extraction
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.0.1
  - cudatoolkit=10.2
  - pip:
      - numpy==1.18.2
      - pandas==1.0.1
      - scikit-learn==0.23.1
      - torch==1.6.0
      - transformers==4.4.2
      - tokenizers==0.10.1
      - tqdm==4.48.0
      - six==1.15.0
