name: ufd
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.0.1
  - pip:
    - polyaxon-client==0.5.6
    - torch==1.8.1
    - torchvision==0.9.1
    - transformers==4.4.2
    - tokenizers==0.10.1
    - sentencepiece==0.1.95
    - numpy
    - wandb