---
version: 1

kind: experiment

build:
  dockerfile: polyaxon/docker/experiment.df
  context: .

environment:
  resources:
    gpu:
      requests: 1
      limits: 1
  persistence:
    data: ["data"]
  configmap_refs: ["sgnlp-wandb-api-key"]

logging:
  level: DEBUG

run:
  cmd: python -m train;