---
version: 1

kind: experiment

build:
  dockerfile: polyaxon/lsr/experiment.Dockerfile

environment:
  configmap_refs: ["sgnlp-wandb-api-key"]
  persistence:
    data: ["100e-nlp-lab-data"]
  resources:
    gpu:
      requests: 1
      limits: 1

framework: pytorch

logging:
  level: INFO

run:
  cmd: python -m sgnlp.models.lsr.train \
    --train_file="/polyaxon-data/workspace/jonheng/lsr/docred/train_annotated.json" \
    --validation_file="/polyaxon-data/workspace/jonheng/lsr/docred/dev.json" \
    --output_dir="/polyaxon-data/workspace/jonheng/lsr/experiment-output/bigger_batch" \
    --metadata_dir="/polyaxon-data/workspace/jonheng/lsr/metadata" \
    --pretrained_embeddings_path="/polyaxon-data/workspace/jonheng/lsr/metadata/vec.npy" \
    --batch_size=16 \
    --num_epoch=100 \
    --seed=64 \
    --evaluate_epoch=20 \
    --weight_decay=0.01