---
version: 1

kind: experiment

build:
  dockerfile: polyaxon/lif_3way_ap/experiment.Dockerfile

environment:
  persistence:
    data: [ "100e-nlp-lab-data" ]
  resources:
    gpu:
      requests: 1
      limits: 1

framework: pytorch

logging:
  level: INFO

run:
  cmd: allennlp train \
    /polyaxon-data/workspace/jonheng/lif-3way-ap/lif_3way_ap_polyaxon.json \
    -s /polyaxon-data/workspace/jonheng/lif-3way-ap/exp-4
    --include-package sgnlp.models.lif_3way_ap